version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: /frontend
    registries: "*"
    schedule:
      interval: weekly
    open-pull-requests-limit: 15
    groups:
      dependencies:
        update-types:
          - minor
          - patch
          - major
  - package-ecosystem: "composer"
    directory: /backend
    registries: "*"
    schedule:
      interval: weekly
    open-pull-requests-limit: 15
    groups:
      dependencies:
        update-types:
          - minor
          - patch
          - major
